name: General Issue
description: Feature, enhancement or general suggestion for the project
title: "[ <<ISSUE_NUMBER>> - [IDEA] ] - Some title here"

body:
  - type: textarea
    attributes:
      label: 🚀 Description
      placeholder: |
        You can describe with a clear and concise description of:
        * what the problem is
        * what you want to happen
        * any alternative solutions or features you've considered
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✍️ Context
      placeholder: |
        A short description of the context of the task, why it is important and how it fits into the overall project.
    validations:
      required: false

  - type: textarea
    attributes:
      label: 📝 Tasks
      placeholder: |
        - [ ] some task here
        - [ ] some task here
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📷 References / 🔗 Attachments
      placeholder: |
        You can attach some screenshots or links here.
        * Desktop
        * Mobile
        * Links
        * [some link]()
    validations:
      required: false
